"""Add posted_time to Job model

Revision ID: 3b43af4bb3f0
Revises: c19909d17ff3
Create Date: 2025-07-25 15:11:32.477179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b43af4bb3f0'
down_revision = 'c19909d17ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('posted_time')

    # ### end Alembic commands ###
